# Generated by Django 4.0.2 on 2022-03-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_clothingsize_alter_item_image_item_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingsize',
            old_name='size',
            new_name='name',
        ),
    ]
